import type { Metadata } from "next";
// 1. Google Fontsから丸ゴシック体をインポート
import { M_PLUS_Rounded_1c } from "next/font/google";
import "./globals.css";

// 2. フォントの設定（太さや読み込み設定）
const mPlus = M_PLUS_Rounded_1c({
  subsets: ["latin"], // 日本語は自動で読み込まれます
  weight: ["400", "700", "800"], // 普通、太字、極太
  preload: false, // 日本語フォントは重いのでpreloadをオフにするのが無難
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* 3. bodyタグにフォントクラスを適用 */}
      <body className={mPlus.className}>
        {children}
      </body>
    </html>
  );
}